image: thistntsquid/alpine-py-curl-zip:latest

before_script:
   - echo "Process start"
   
after_script:
  - echo "End of Process"
  
stages:
  - test
  # - package
   
test:
 stage: test
 script: 
   - echo "Testing started"
#   - curl https://files.corecrafted.net/ci/test.py | python3 -
   - echo "Testing Skipped for now"

# package:
#  stage: package
#  artifacts:
#     paths:
#       - ./sem-resourcepack
#  script:
#    - echo "Packaging files to artifact..."
#    - mkdir sem-resourcepack
#    - mv assets sem-resourcepack
#    - mv LICENSE sem-resourcepack
#    - mv pack.mcmeta sem-resourcepack
#    - mv pack.png sem-resourcepack